const express = require('express')
const userRouter = require('./routes/user-router')
const routeRouter = express.Router()
const articleRouter = require('./routes/articleRouter')
const { login, register, logout, newTokens } = require('./controllers/auth')
const { initalRoute} = require('./controllers/route-controllers')
const { authMiddleWare } = require('./utils')
const { GetArticleDataNotSchedule } = require('./controllers/article')
require('dotenv').config()

routeRouter.use('/user', userRouter)
routeRouter.use('/article',articleRouter)
routeRouter.get('/', initalRoute)
routeRouter.post('/login', login)
routeRouter.post('/register', register)
routeRouter.post('/logout', logout)
routeRouter.post('/url',authMiddleWare, GetArticleDataNotSchedule)
routeRouter.get('/tokens',newTokens)

module.exports=routeRouter